const allTrialSets = {
    "0": [
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_0-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_0-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_0-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_2.5-cle_5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_2.5-cle_0.5",
            "sym_0.8-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_1",
            "sym_0.8-alg_5-cle_1"
        ],
        [
            "sym_1.4-alg_1-cle_1",
            "sym_2-alg_1-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0-alg_1-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_0.8-alg_0.5-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_2-alg_1-cle_5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_2.5",
            "sym_0.8-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_5-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_1.4-alg_1-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_0.5",
            "sym_1.4-alg_1-cle_5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_0.2-alg_5-cle_0.5"
        ],
        [
            "sym_2-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_1"
        ],
        [
            "sym_0.2-alg_2.5-cle_1",
            "sym_0.8-alg_2.5-cle_1"
        ],
        [
            "sym_0.2-alg_2.5-cle_2.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_1",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0-alg_0.5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_2.5",
            "sym_0-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0-alg_1-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_1",
            "sym_1.4-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_1.4-alg_0.5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_0.2-alg_2.5-cle_0.5"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0-alg_2.5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_5",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_5",
            "sym_1.4-alg_1-cle_5"
        ],
        [
            "sym_2-alg_1-cle_1",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_2-alg_1-cle_1",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_2.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.2-alg_1-cle_5",
            "sym_0.8-alg_1-cle_5"
        ],
        [
            "sym_2-alg_1-cle_0.5",
            "sym_2-alg_1-cle_1"
        ],
        [
            "sym_1.4-alg_5-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_1.4-alg_2.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_0.5"
        ],
        [
            "sym_1.4-alg_1-cle_5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_0-alg_5-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.2-alg_5-cle_0.5",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_2.5",
            "sym_0.8-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0-alg_1-cle_0.5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_0.2-alg_1-cle_1"
        ],
        [
            "sym_0.8-alg_5-cle_1",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_2.5",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_5-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_0.8-alg_0.5-cle_1"
        ],
        [
            "sym_2-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_2-alg_1-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_0-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_0.5",
            "sym_1.4-alg_5-cle_0.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_5",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_1",
            "sym_2-alg_1-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_2.5",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_1.4-alg_1-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_0-alg_5-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_1.4-alg_0.5-cle_2.5"
        ],
        [
            "sym_2-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_0.2-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_0.2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_0-alg_5-cle_2.5"
        ]
    ],
    "1": [
        [
            "sym_0.2-alg_1-cle_5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_2.5-cle_2.5",
            "sym_0.2-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.2-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.2-alg_2.5-cle_0.5"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_0.8-alg_0.5-cle_2.5"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_2-alg_0.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_0.2-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_1.4-alg_0.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_2-alg_0.5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_1",
            "sym_0.8-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_1.4-alg_0.5-cle_5"
        ],
        [
            "sym_0-alg_1-cle_5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_0.8-alg_2.5-cle_1",
            "sym_1.4-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_0-alg_5-cle_0.5"
        ],
        [
            "sym_2-alg_2.5-cle_1",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_5-cle_0.5",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_0.8-alg_0.5-cle_5"
        ],
        [
            "sym_2-alg_0.5-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_0-alg_2.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_0.5-cle_2.5",
            "sym_1.4-alg_0.5-cle_5"
        ],
        [
            "sym_2-alg_5-cle_0.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_5-cle_1",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_2-alg_0.5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_5",
            "sym_0-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_5-cle_0.5",
            "sym_1.4-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_5-cle_5",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_2-alg_0.5-cle_1",
            "sym_2-alg_0.5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_0.8-alg_1-cle_0.5"
        ],
        [
            "sym_0.8-alg_5-cle_0.5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_2.5",
            "sym_1.4-alg_0.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_5",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_1.4-alg_5-cle_0.5"
        ],
        [
            "sym_2-alg_2.5-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_0.5"
        ],
        [
            "sym_2-alg_1-cle_0.5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_0-alg_1-cle_5",
            "sym_0.8-alg_1-cle_5"
        ],
        [
            "sym_1.4-alg_1-cle_1",
            "sym_1.4-alg_2.5-cle_1"
        ],
        [
            "sym_2-alg_2.5-cle_1",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_1.4-alg_1-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_1.4-alg_1-cle_0.5"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_0-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_0.5",
            "sym_0.8-alg_5-cle_0.5"
        ],
        [
            "sym_2-alg_1-cle_1",
            "sym_2-alg_1-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_2.5",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_0.8-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_0.5"
        ],
        [
            "sym_0.2-alg_5-cle_0.5",
            "sym_0.2-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0.2-alg_1-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_2.5",
            "sym_0.2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_0.8-alg_1-cle_5"
        ],
        [
            "sym_0-alg_5-cle_2.5",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_0.8-alg_1-cle_5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_2.5",
            "sym_1.4-alg_1-cle_2.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_5-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_2-alg_1-cle_1"
        ],
        [
            "sym_2-alg_1-cle_0.5",
            "sym_2-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_2-alg_1-cle_0.5"
        ],
        [
            "sym_0.2-alg_5-cle_0.5",
            "sym_0.2-alg_5-cle_1"
        ],
        [
            "sym_0.2-alg_2.5-cle_2.5",
            "sym_0.2-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_1.4-alg_0.5-cle_2.5"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0-alg_5-cle_1"
        ],
        [
            "sym_0-alg_1-cle_5",
            "sym_1.4-alg_1-cle_5"
        ]
    ],
    "2": [
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_0.8-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_0.5",
            "sym_2-alg_1-cle_0.5"
        ],
        [
            "sym_2-alg_0.5-cle_0.5",
            "sym_2-alg_1-cle_0.5"
        ],
        [
            "sym_0.8-alg_1-cle_2.5",
            "sym_0.8-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_1",
            "sym_1.4-alg_1-cle_1"
        ],
        [
            "sym_0-alg_2.5-cle_5",
            "sym_0.2-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_2.5",
            "sym_0.8-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_0.5",
            "sym_0.8-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_5-cle_1",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_0.2-alg_2.5-cle_1",
            "sym_0.2-alg_2.5-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_1",
            "sym_1.4-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_5",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_0-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_2-alg_1-cle_1"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_0.2-alg_1-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_0.5"
        ],
        [
            "sym_2-alg_1-cle_2.5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_1.4-alg_1-cle_1"
        ],
        [
            "sym_0.8-alg_0.5-cle_2.5",
            "sym_0.8-alg_0.5-cle_5"
        ],
        [
            "sym_2-alg_0.5-cle_2.5",
            "sym_2-alg_0.5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_2.5",
            "sym_0.8-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_2-alg_0.5-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_2.5",
            "sym_2-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_0.5",
            "sym_1.4-alg_1-cle_1"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_0.2-alg_1-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_2.5",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_5-cle_5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_0.2-alg_0.5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_0.8-alg_0.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_1.4-alg_0.5-cle_1"
        ],
        [
            "sym_2-alg_0.5-cle_5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_5-cle_2.5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_0.2-alg_2.5-cle_0.5"
        ],
        [
            "sym_2-alg_0.5-cle_0.5",
            "sym_2-alg_2.5-cle_0.5"
        ],
        [
            "sym_2-alg_2.5-cle_2.5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_0.8-alg_2.5-cle_1"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_0.2-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_1",
            "sym_1.4-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0.2-alg_0.5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0-alg_0.5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_2-alg_1-cle_2.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_2.5",
            "sym_2-alg_0.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_5",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_1.4-alg_2.5-cle_1",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_1",
            "sym_1.4-alg_1-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_1.4-alg_0.5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_0-alg_1-cle_2.5"
        ],
        [
            "sym_2-alg_1-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_2-alg_1-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0.2-alg_0.5-cle_0.5"
        ],
        [
            "sym_2-alg_5-cle_0.5",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_2-alg_0.5-cle_5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_2.5",
            "sym_2-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_0-alg_5-cle_2.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_0.8-alg_0.5-cle_2.5"
        ],
        [
            "sym_2-alg_1-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_1.4-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_0.5"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0-alg_2.5-cle_1"
        ],
        [
            "sym_2-alg_1-cle_0.5",
            "sym_2-alg_1-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_1",
            "sym_0.2-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_5-cle_0.5",
            "sym_0.8-alg_5-cle_1"
        ],
        [
            "sym_0.2-alg_2.5-cle_1",
            "sym_1.4-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_0.8-alg_1-cle_2.5"
        ]
    ],
    "3": [
        [
            "sym_1.4-alg_5-cle_0.5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_0.8-alg_2.5-cle_0.5"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0-alg_5-cle_0.5"
        ],
        [
            "sym_1.4-alg_2.5-cle_5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_1.4-alg_5-cle_1",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_1.4-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0.8-alg_0.5-cle_1"
        ],
        [
            "sym_1.4-alg_2.5-cle_0.5",
            "sym_1.4-alg_5-cle_0.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_0.2-alg_5-cle_0.5"
        ],
        [
            "sym_0.8-alg_1-cle_2.5",
            "sym_0.8-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_0.2-alg_1-cle_2.5"
        ],
        [
            "sym_2-alg_1-cle_2.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_2.5-cle_5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_2.5",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_5",
            "sym_0.8-alg_1-cle_5"
        ],
        [
            "sym_1.4-alg_5-cle_0.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_0.5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_0-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_0.8-alg_5-cle_0.5"
        ],
        [
            "sym_2-alg_5-cle_0.5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_2-alg_5-cle_1",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_2.5",
            "sym_0-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_2.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_0.5",
            "sym_0.8-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_0-alg_5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_5",
            "sym_0-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.2-alg_1-cle_0.5"
        ],
        [
            "sym_0.2-alg_5-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_2.5",
            "sym_0-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_2.5",
            "sym_1.4-alg_1-cle_2.5"
        ],
        [
            "sym_2-alg_2.5-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_5",
            "sym_0.2-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_1.4-alg_0.5-cle_1"
        ],
        [
            "sym_1.4-alg_2.5-cle_5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_0.8-alg_1-cle_1"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_0.2-alg_2.5-cle_1"
        ],
        [
            "sym_0.2-alg_1-cle_5",
            "sym_0.2-alg_2.5-cle_5"
        ],
        [
            "sym_2-alg_0.5-cle_1",
            "sym_2-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_5-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_0.2-alg_5-cle_1"
        ],
        [
            "sym_2-alg_0.5-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_0.8-alg_5-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_1",
            "sym_0.8-alg_1-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_1",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_1.4-alg_2.5-cle_2.5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_0.2-alg_5-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_1.4-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_5",
            "sym_2-alg_0.5-cle_5"
        ],
        [
            "sym_0.8-alg_5-cle_2.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_2.5-cle_2.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.8-alg_0.5-cle_0.5"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_2-alg_0.5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_1.4-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_2.5-cle_2.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_1.4-alg_2.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_1"
        ],
        [
            "sym_0-alg_2.5-cle_2.5",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_0-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_0.2-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0.8-alg_1-cle_0.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_0.2-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_1",
            "sym_0.8-alg_1-cle_5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_0-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_5-cle_5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_2-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_5"
        ]
    ],
    "4": [
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_0.8-alg_1-cle_1"
        ],
        [
            "sym_0.2-alg_1-cle_2.5",
            "sym_0.8-alg_1-cle_2.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_1",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_1.4-alg_5-cle_1",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_1",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_0.2-alg_1-cle_2.5"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_0.8-alg_0.5-cle_1"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_0-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_5",
            "sym_0.2-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_5-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_2.5-cle_2.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_5-cle_1",
            "sym_0.8-alg_5-cle_1"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_0.8-alg_2.5-cle_0.5"
        ],
        [
            "sym_0-alg_5-cle_1",
            "sym_0-alg_5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_1",
            "sym_0-alg_0.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_5-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_0-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.2-alg_5-cle_0.5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_2-alg_1-cle_0.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_1",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_1.4-alg_1-cle_0.5"
        ],
        [
            "sym_2-alg_0.5-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_0.5-cle_5",
            "sym_1.4-alg_0.5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_2.5",
            "sym_0.2-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_0-alg_5-cle_1"
        ],
        [
            "sym_0.2-alg_0.5-cle_5",
            "sym_0.2-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_0.2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_1.4-alg_1-cle_1",
            "sym_1.4-alg_1-cle_5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_0-alg_1-cle_5"
        ],
        [
            "sym_1.4-alg_5-cle_0.5",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_2-alg_2.5-cle_0.5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_1.4-alg_2.5-cle_1",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_0.8-alg_1-cle_0.5"
        ],
        [
            "sym_2-alg_5-cle_2.5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_1.4-alg_1-cle_2.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_2-alg_0.5-cle_1",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_5",
            "sym_1.4-alg_1-cle_5"
        ],
        [
            "sym_0-alg_5-cle_1",
            "sym_2-alg_5-cle_1"
        ],
        [
            "sym_2-alg_0.5-cle_2.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_1-cle_1",
            "sym_0.8-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_0.8-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_2.5",
            "sym_0.2-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_2.5",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_0-alg_1-cle_5"
        ],
        [
            "sym_0-alg_1-cle_0.5",
            "sym_2-alg_1-cle_0.5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_0.2-alg_1-cle_2.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_0.5",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_1",
            "sym_1.4-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_5-cle_2.5",
            "sym_1.4-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_0.2-alg_2.5-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_5",
            "sym_2-alg_0.5-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_1.4-alg_1-cle_0.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_2.5",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_1",
            "sym_2-alg_2.5-cle_1"
        ],
        [
            "sym_1.4-alg_1-cle_5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_0.5",
            "sym_0-alg_2.5-cle_1"
        ],
        [
            "sym_0.2-alg_1-cle_5",
            "sym_0.2-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.2-alg_0.5-cle_1"
        ]
    ],
    "5": [
        [
            "sym_0.8-alg_5-cle_1",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_0.2-alg_1-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_2.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_2.5",
            "sym_0.8-alg_1-cle_2.5"
        ],
        [
            "sym_0.2-alg_1-cle_0.5",
            "sym_0.2-alg_1-cle_1"
        ],
        [
            "sym_1.4-alg_1-cle_0.5",
            "sym_1.4-alg_1-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_5",
            "sym_1.4-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_1",
            "sym_0.2-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_5",
            "sym_0.8-alg_0.5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_5",
            "sym_2-alg_0.5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_2.5",
            "sym_0.2-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_0.5-cle_1",
            "sym_2-alg_0.5-cle_1"
        ],
        [
            "sym_0.8-alg_2.5-cle_1",
            "sym_0.8-alg_5-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0.8-alg_0.5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_5",
            "sym_0-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_0.8-alg_5-cle_0.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_0.2-alg_0.5-cle_5"
        ],
        [
            "sym_0.2-alg_0.5-cle_0.5",
            "sym_0.2-alg_0.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_0.5",
            "sym_1.4-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_5-cle_1",
            "sym_0-alg_5-cle_2.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_1",
            "sym_2-alg_0.5-cle_1"
        ],
        [
            "sym_1.4-alg_0.5-cle_0.5",
            "sym_1.4-alg_0.5-cle_1"
        ],
        [
            "sym_1.4-alg_2.5-cle_1",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_1-cle_2.5",
            "sym_0.8-alg_5-cle_2.5"
        ],
        [
            "sym_0.8-alg_0.5-cle_0.5",
            "sym_0.8-alg_0.5-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_0.5"
        ],
        [
            "sym_0.2-alg_0.5-cle_2.5",
            "sym_0.2-alg_5-cle_2.5"
        ],
        [
            "sym_2-alg_5-cle_1",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_1.4-alg_2.5-cle_1",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_2-alg_0.5-cle_0.5",
            "sym_2-alg_0.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_1-cle_2.5",
            "sym_0.2-alg_5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_2.5",
            "sym_1.4-alg_1-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_5",
            "sym_0.8-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_0-alg_2.5-cle_5"
        ],
        [
            "sym_0.2-alg_2.5-cle_0.5",
            "sym_0.8-alg_2.5-cle_0.5"
        ],
        [
            "sym_0.8-alg_2.5-cle_2.5",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_2.5",
            "sym_1.4-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_5",
            "sym_2-alg_2.5-cle_5"
        ],
        [
            "sym_0-alg_5-cle_1",
            "sym_0.2-alg_5-cle_1"
        ],
        [
            "sym_1.4-alg_1-cle_0.5",
            "sym_1.4-alg_2.5-cle_0.5"
        ],
        [
            "sym_1.4-alg_0.5-cle_1",
            "sym_1.4-alg_5-cle_1"
        ],
        [
            "sym_0.8-alg_2.5-cle_5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_1.4-alg_2.5-cle_2.5",
            "sym_2-alg_2.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_5",
            "sym_2-alg_1-cle_5"
        ],
        [
            "sym_0-alg_5-cle_0.5",
            "sym_0.8-alg_5-cle_0.5"
        ],
        [
            "sym_0-alg_1-cle_5",
            "sym_0-alg_5-cle_5"
        ],
        [
            "sym_2-alg_2.5-cle_2.5",
            "sym_2-alg_5-cle_2.5"
        ],
        [
            "sym_2-alg_2.5-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_1.4-alg_0.5-cle_2.5",
            "sym_1.4-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_5-cle_2.5",
            "sym_1.4-alg_5-cle_2.5"
        ],
        [
            "sym_2-alg_0.5-cle_1",
            "sym_2-alg_1-cle_1"
        ],
        [
            "sym_2-alg_0.5-cle_5",
            "sym_2-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_2.5",
            "sym_2-alg_1-cle_2.5"
        ],
        [
            "sym_0-alg_1-cle_1",
            "sym_0.8-alg_1-cle_1"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_0-alg_0.5-cle_1"
        ],
        [
            "sym_1.4-alg_2.5-cle_0.5",
            "sym_1.4-alg_2.5-cle_5"
        ],
        [
            "sym_0.8-alg_0.5-cle_1",
            "sym_0.8-alg_2.5-cle_1"
        ],
        [
            "sym_0.8-alg_1-cle_0.5",
            "sym_0.8-alg_1-cle_1"
        ],
        [
            "sym_0.8-alg_0.5-cle_5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.2-alg_5-cle_5",
            "sym_0.8-alg_5-cle_5"
        ],
        [
            "sym_0.8-alg_2.5-cle_1",
            "sym_0.8-alg_2.5-cle_2.5"
        ],
        [
            "sym_0.2-alg_1-cle_2.5",
            "sym_0.2-alg_1-cle_5"
        ],
        [
            "sym_0.2-alg_1-cle_1",
            "sym_0.2-alg_1-cle_5"
        ],
        [
            "sym_1.4-alg_0.5-cle_5",
            "sym_1.4-alg_1-cle_5"
        ],
        [
            "sym_0-alg_0.5-cle_0.5",
            "sym_1.4-alg_0.5-cle_0.5"
        ],
        [
            "sym_0-alg_2.5-cle_1",
            "sym_0.2-alg_2.5-cle_1"
        ]
    ],
    "6": [
        [
            "sym_2-alg_0.5-cle_2.5",
            "sym_2-alg_1-cle_2.5"
        ],
        [
            "sym_1.4-alg_5-cle_0.5",
            "sym_2-alg_5-cle_0.5"
        ],
        [
            "sym_0.2-alg_2.5-cle_1",
            "sym_0.2-alg_2.5-cle_2.5"
        ],
        [
            "sym_1.4-alg_1-cle_2.5",
            "sym_2-alg_1-cle_2.5"
        ]
    ]
}
let sumTrialsToUse;

let trials;
let trialOrder;
let numTrials;


let currentTrialIndex = -1;
const pageDelay = 0;
const trialDelay = 0;
let startTime;
let results;

setTimeout(() => $("#continueButton").prop("disabled", false), pageDelay);

if (window.screen.height < 600 || window.screen.width < 1000) {
    $("#consentPage").hide();
    $("#screenSizeWarning").show();
    $("#screenSize").text(`Your current screen size is ${window.screen.width}x${window.screen.height}.`);
}

function databaseGetStartCall() {

    sumTrialsToUse = 0;
    $.ajax({
        type: "GET",
        url: "https://script.google.com/macros/s/AKfycbwfE05MFtFW3yYF4iMepcpL172KTgfy39N4Nf0RnRwhHAKfE3i_JlT9aWjhWLotNYrx/exec",
        async: false,
        data: {get_param: 'start'},
        dataType: 'json',
        success: function (response) {
            sumTrialsToUse = response.post;
        }
    });
}

function continueButtonPressed() {
    $("#consentPage").hide();
    $("#instructionPage").show();
    $("#welcomeHeading").hide();
    setTimeout(() => $("#startButton").prop("disabled", false), pageDelay);
}

function startButtonPressed() {
    $("#instructionPage").hide();
    $("#referencePage").show();
    setTimeout(() => $("#trialStartButton").prop("disabled", false), pageDelay);
}

function trialStartButtonPressed() {
    $("#referencePage").hide();

    databaseGetStartCall();
    results = []
    startTime = new Date();
    trials =  allTrialSets[sumTrialsToUse];
    console.log(trials)
    trialOrder = [...trials.keys()];
    shuffleArray(trialOrder);
    numTrials = trials.length;

    startTrials();
}

function startTrials() {
    $("#trialPage").show();
    setButtonEnableTimer("realismButton", trialDelay);
    nextTrial();
}

function realismSubmit(button) {
    setButtonEnableTimer("realismButton", trialDelay);
    results.push(getTrialResult(button));
    nextTrial();
}

function getTrialResult(button) {
    let imageString = "";
    if (button === "Left") {
        imageString = $("#leftImage").attr("src");
    } else {
        imageString = $("#rightImage").attr("src");
    }
    return {
        trialNum: trialOrder[currentTrialIndex],
        selectedImage: imageString.substring(4, imageString.length - 4),
        selectedButton: button
    }
}

function nextTrial() {
    currentTrialIndex += 1;
    if (currentTrialIndex >= numTrials) {
        finishTrials();
    } else {
        $("#trialNumber").text(`Trial ${currentTrialIndex + 1} of ${numTrials}`)
        if (Math.random() < 0.5) {
            $("#leftImage").attr("src", `img/${trials[trialOrder[currentTrialIndex]][0]}.jpg`);
            $("#rightImage").attr("src", `img/${trials[trialOrder[currentTrialIndex]][1]}.jpg`);
        } else {
            $("#leftImage").attr("src", `img/${trials[trialOrder[currentTrialIndex]][1]}.jpg`);
            $("#rightImage").attr("src", `img/${trials[trialOrder[currentTrialIndex]][0]}.jpg`);
        }
    }
}

function finishTrials() {
    $("#trialPage").hide();
    $("#demographicsPage").show();
}

function verifyAndGatherData() {
    let potentialAge  = parseInt($("input[name=age]").val(), 10);
    let potentialCountry = $("input[name=country]").val();
    
    if (Number.isInteger(potentialAge) && potentialCountry) {
        let data = {
            gender: $("select[name=gender]").find(":selected").text(),
            age: potentialAge,
            education: $("select[name=education]").find(":selected").text(),
            country: potentialCountry,
            experience: $("select[name=experience]").find(":selected").text(),
            vision: $("select[name=vision]").find(":selected").text(),
            comments: $("textarea[name=comments]").val(),
            duration: 0.001 * (new Date() - startTime),
            subTrial:parseInt(sumTrialsToUse, 10),
            trialResults: results
        }

        $("input[name=Data]").val(JSON.stringify(data));
        $("#dataForm").submit();
        $("#demographicsPage").hide();
    } else {
        alert("Incorrect data, correct any errors and try again.");
    }
}

function setButtonEnableTimer(className, delay) {
    $(`.${className}`).prop("disabled", true);
    setTimeout(() => $(`.${className}`).prop("disabled", false), delay);
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const temp = array[i];
      array[i] = array[j];
      array[j] = temp;
    }
}